version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - bodyclose
    - nilerr
    - exhaustive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
